apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - canary.yaml
  # - nginx-ingress.yaml # Commented out because we're using the default ingress controller of minikube

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

